title: 下一秒想去看海
description: 一些寫給未來、城市、夜晚和低電量生活的文字。
author: Angze Li
lang: zh-Hant
timezone: Europe/London
permalink: /writing/:year/:month/:day/:title/
markdown: kramdown
future: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: page
